### PR TITLE
Commit add confirmation to stop tracks.

### PR DESCRIPTION
**Pull request by stevegdavis**
Added confirmation dialog to FragmentRecordingControls.java->ontoggleRecordGeoPoint() method and associated dialog message string.

### CODE REVIEW

**Comment by stevegdavis** [comment]
Sorry, you can ignore the build files changes as I didn't realise the commit had included them (they were changed to get the code to build).

**Comment by JLJu** [comment]
You are welcome! Thank you for your commit!

**Comment by GrazianoCapelli** [comment]
Welcome to BasicAirData!
Writing code, sooner or later, everyone falls into the Great Doubt:
_Needs confirmation or not needs confirmation? That is the question._
We long thought about this topic, but sadly there is no right answer.

Google Android guidelines suggest to use dialogs sparingly because they are interruptive, and also suggests in general to Reduce interruption during the user interaction.
We decide, trying to follow that guidelines, to tend toward the "conscious user" approach.
Hence we choose to add interruption dialogs only for not reversible operations, in our case "Finish a track", "Delete a track" or "delete a file".
The remaining operations (like share, view, export tracks - pause/record and add placemark - Access to settings and about screen) can be easily reverted, hence they were left freely accessible to the user without interruption.

This is the reason why we are thinking to not merge this pull request into the master branch.
In any case We strongly hope to collaborate (again) to develop GPS Logger.
For now, thanks for your time and for your code!

**Comment by stevegdavis** [comment]
Ok that is fair comment.

**Pull request closed without merging**
