### PR TITLE
#143 Add the ellipsis if the viewer's name is too long

### PR DESCRIPTION
**Pull request by beiko14**
Screenshot_20210626-102058

### CODE REVIEW

**Comment by beiko14** [comment]
Is this the right branch for the pull request?

**Comment by GrazianoCapelli** [comment]
The best approach would be to fork, create a new feature branch into forked repo, make changes and request the pull into our develop branch. Anyway, your approach is OK too.

Let's speak of code:
you trunk the app name string to the arbitrary length of 18 chars, basing on your device appearance.
But any device type has a different space for it, thus a more general solution should be implemented.
I suggest instead to act on xml using the `ellipsize` property, without changing the Java code.

**Comment by beiko14** [comment]
Thank you for the help. I used the ellipsize property like you mentioned.

Next time I'm going to create a new feature branch.

**Comment by GrazianoCapelli** [comment]
It looks perfect, thanks for your contribution!

**Pull request merged**
