### PR TITLE
create values-ko and translate english to korean

### PR DESCRIPTION
**Pull request by qylee**
add korean strings.xml

### CODE REVIEW

**Comment by GrazianoCapelli** [comment]
Dear @qylee,
first of all thanks for your time and for your precious contribution.

I would to inform you that we chosen to use the [Crowdin](https://crowdin.com/project/gpslogger) platform to make, manage and maintain the localizations, in order to have a larger base of translators: this way also non-developers can translate and keep updated the strings of the application.
For this reason, although it is correct, we cannot accept your pull request.

We know that the importation of the strings is an extra work for the develop team but after some years, thanks to many volunteers, we have the possibility to include 10 localizations as confirmation that we chosen the right approach.

I added the [Korean](https://crowdin.com/project/gpslogger/ko) language to the language list in case you would like to add your translated strings into the localization platform; we would be glad to add the Korean language to the next app update.
Please read carefully the inclusion process on the Description section of the Crowdin homepage.

As information: if you would like to be informed and discuss the new strings across the next updates, you can subscribe our GitHub translation channel (https://github.com/BasicAirData/GPSLogger/issues/16).

**Comment by qylee** [comment]
> Dear @qylee, first of all thanks for your time and for your precious contribution.
> 
> I would to inform you that we chosen to use the [Crowdin](https://crowdin.com/project/gpslogger) platform to make, manage and maintain the localizations, in order to have a larger base of translators: this way also non-developers can translate and keep updated the strings of the application. For this reason, although it is correct, we cannot accept your pull request.
> 
> We know that the importation of the strings is an extra work for the develop team but after some years, thanks to many volunteers, we have the possibility to include 10 localizations as confirmation that we chosen the right approach.
> 
> I added the [Korean](https://crowdin.com/project/gpslogger/ko) language to the language list in case you would like to add your translated strings into the localization platform; we would be glad to add the Korean language to the next app update. Please read carefully the inclusion process on the Description section of the Crowdin homepage.
> 
> As information: if you would like to be informed and discuss the new strings across the next updates, you can subscribe our GitHub translation channel (#16).

Dear @GrazianoCapelli 
Okay. 
I agree with your choice. We will work on localization on the Crowdin platform.
Thanks for adding the Korean language.
I

**Comment by GrazianoCapelli** [comment]
We noticed that you uploaded the translated strings into Crowdin: thanks for the great work.
Since I don't know Korean, I checked them with Google Translator (I always do a check of translations to be sure about the meanings of them, in order to try to avoid completely wrong translations) and I added some notes. My notes could be wrong or not, please be patient and read them when you have the time.

I agree with your choice to keep the international notation of the units of measurement (m, s, km/h, and so on).

I have a general question about your translation: you often added a "." at the end of the strings also if it is not present on the original string; it is necessary in Korean language, or we can remove them when they are not present into the original string?

**Comment by qylee** [comment]
> We noticed that you uploaded the translated strings into Crowdin: thanks for the great work. Since I don't know Korean, I checked them with Google Translator (I always do a check of translations to be sure about the meanings of them, in order to try to avoid completely wrong translations) and I added some notes. My notes could be wrong or not, please be patient and read them when you have the time.
> 
> I agree with your choice to keep the international notation of the units of measurement (m, s, km/h, and so on).
> 
> I have a general question about your translation: you often added a "." at the end of the strings also if it is not present on the original string; it is necessary in Korean language, or we can remove them when they are not present into the original string?

It is a rule to put a period(.) in Korean sentences.
I put periods on purpose.

However, there are cases where periods are used inconsistently. I fixed this in crowdin.
Thanks for raising the issue.

**Comment by GrazianoCapelli** [comment]
We are close to release the update v3.1.7 of the app, and this could be a good occasion to include the Korean language.
There are some issues yet open in Crowdin; it would be great if you could spend some minutes in the next days to check, process and solve them, so we can include it.

Anyway, feel free to contribute compatibly with your time and to your liking.
We have no scheduler. The Korean language will be included if / when it will be ready: if not into v3.1.7, maybe it will be included later.

I close this pull request.
Feel free to comment here or reopen it in case of need.

Thanks again for your contribution!

**Pull request closed without merging**
