### PR TITLE
Be explicit when using default Locale

### PR DESCRIPTION
**Pull request by tomlayg6**

### CODE REVIEW

**Comment by GrazianoCapelli** [comment]
Referring to [SimpleDateFormat](https://developer.android.com/reference/java/text/SimpleDateFormat) documentation, We are using only numeric Format for Presentation.
Where can the missing Locale cause some Issues on the App?

I think it could be a good idea to specify the **Locale.US** in Exporter's Output instead.
In Fact [Locale Documentation](https://developer.android.com/reference/java/util/Locale#locale-data) sees that:

> The default locale is not appropriate for machine-readable output. The best choice there is usually Locale.US – this locale is guaranteed to be available on all devices, and the fact that it has no surprising special cases and is frequently used (especially for computer-computer communication) means that it tends to be the most efficient choice too.

This Case you are right, and we should add it in order to avoid any possible Bug.

**Comment by tomlayg6** [comment]
The PR does not change behaviour, it just makes the Locale explicit.

Note that  [Locale Documentation](https://developer.android.com/reference/java/util/Locale#locale-data) states:

> The default locale is appropriate for tasks that involve presenting data to the user. In this case, you want to use the user's date/time formats, number formats, rules for conversion to lowercase, and so on. In this case, it's safe to use the convenience methods.

So I don't think Locale.US is appropriate here.

**Comment by GrazianoCapelli** [comment]
> Note that there are many convenience methods that automatically use the default locale, but using them may lead to subtle bugs.
> The default locale is appropriate for tasks that involve presenting data to the user. In this case, you want to use the user's date/time formats, number formats, rules for conversion to lowercase, and so on. In this case, it's safe to use the convenience methods. 
>
> The default locale is not appropriate for machine-readable output. The best choice there is usually Locale.US – this locale is guaranteed to be available on all devices, and the fact that it has no surprising special cases and is frequently used (especially for computer-computer communication) means that it tends to be the most efficient choice too

Thus, to sum up:
- We can leave the Method as is (without explicit the Locale) where the Data is presented to Users: nothing suggest the explicit use in the Documentation (not even Lint in Android Studio)
- We should explicitly use `Locale.US` where the Data goes into a File (like GPX or KML) or into the DataBase, that are intended for machine-readable I/O

**Comment by tomlayg6** [comment]
There are two aspects to this:
* ensuring that machine output has a consistent format. For such cases, a fixed Locale should be used.
Ideally use [Local.ROOT](https://developer.android.com/reference/java/util/Locale#ROOT) to avoid cultural differences.
* ensuring that visual output is presented in the current locale.

In the former case, a specific Locale must be used.
In the second case, it is not essential to provide a Locale, however the code then gives no clue as to whether the Locale was intentionally omitted, or whether it has been overlooked. For this reason, code checkers report when the parameter is missing. For example, 'gradle lint' complains about SimpleDateFormat. If I use the Inspect code function of Android Studio it also shows the issue.

I think all the instances need to be updated, otherwise the instances without a Locale will continue to generate queries as to why the Locale is missing.

**Pull request merged**
